### ISSUE TITLE
When opening Windows terminal Power line icons or glyph does not appeard.

### ISSUE THREAD

**Issue by narendra-sabhani** [JanDeDobbeleer/oh-my-posh2#232]
On my Machine I have latest preview version of Windows Terminal is installed (v0.11.1121.0).

Every time i opened windows terminal i have to run "Set-Prompt" command to make  Power line icons or glyph enable or even in new tab it is not showing.

After closing WT i think, it is restoring settings to default. Attached the screenshot for reference.

Am i missing anything?. Please let me know.

![img](https://user-images.githubusercontent.com/63447758/80305680-daffb480-87db-11ea-84df-4aedd8b6ad1c.jpg)

**Comment by njtrentacoste** [comment]
Have you setup your powershell profile?

From the Readme:
>```powershell
>notepad $PROFILE
>```
>
>Append the following lines to your PowerShell profile:
>```powershell
>Import-Module posh-git
>Import-Module oh-my-posh
>Set-Theme <insert the name of your preferred theme here>
>```

**Comment by csrakowski** [comment]
What font are you using?

If I recall correctly the default font Microsoft ships is the "regular" Cascadia Code/Mono which doesn't have the special glyphs embedded in it. If that's the case, changing the font setting to Cascadia Code/Mono PL should fix it. (Downloads here: https://github.com/microsoft/cascadia-code/releases)

**Comment by ahashans** [comment]
I am also having the same issue. I have updated my `powershell $PROFILE` . But it is still the same.
![image](https://user-images.githubusercontent.com/9111609/89120389-c9fbc900-d4d7-11ea-9087-5cdb19871691.png)

**Comment by bhavikbhakta** [comment]
Updating my comment as I resolved it.

1. Download the Cascadia-code font from here: https://github.com/microsoft/cascadia-code
2. Extract and Install the TTF or OTF files for All Users
![image](https://user-images.githubusercontent.com/64099126/89465241-c5394e00-d73f-11ea-96f7-dbc320734538.png)
3. In windows terminal, click the dropdown and click settings
![image](https://user-images.githubusercontent.com/64099126/89465207-b5ba0500-d73f-11ea-8124-5366eccfa12c.png)
4. Add the following line under your PowerShell settings
`"fontFace":  "Cascadia Code PL",`
![image](https://user-images.githubusercontent.com/64099126/89465318-e863fd80-d73f-11ea-85e7-63af3c5f7a9c.png)
5.  Save, and close Windows Terminal.  Relaunch to verify it works
